### ISSUE TITLE
Can I pass pandoc parameters?

### ISSUE THREAD

**Issue by ahmedmohiduet** [raghur/easyblogger#101]
Incase I need pandocs build-in syntax highlight themes. Can I pass pandoc parameters like:
`--standalone` and `--highlight-style=tango` within `easyblogger` command?  
This should in fact give me exactly what I needed for highlighting as per #100.

**Comment by raghur** [comment]
easyblogger uses `pypandoc` wrapper over pandoc binary and easyblogger itself doesn't have a way to specifiy pass through args to pandoc. 

However, it's not hard - this should work in theory:
You can set the pandoc binary used by pypandoc as specified here https://github.com/bebraw/pypandoc#specifying-the-location-of-pandoc-binaries

Then you can create a wrapper pandoc script that adds whatever pandoc args you need additionally and calls the actual pandoc executable.
