### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by snakefromhell** [raghur/easyblogger#12]
Hi, I get this error using command 

easyblogger get -p "post_number" -d markdown --write-files

.easyblogger.credentials present

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/blogger/main.py", line 87, in printPosts
    converted).encode('utf-8',
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 1: ordinal not in range(128)
Sat Mar 10 01:08:34 2018 <Greenlet at 0x7ffba28a09b0: printPosts({u'status': u'LIVE', u'content': u'\nW\u0142a\u015, 'id,title,url', 'markdown', True)> failed with UnicodeEncodeError

```

output of locale

```
LANG=pl_PL.utf8
LANGUAGE=
LC_CTYPE="pl_PL.utf8"
LC_NUMERIC="pl_PL.utf8"
LC_TIME="pl_PL.utf8"
LC_COLLATE="pl_PL.utf8"
LC_MONETARY="pl_PL.utf8"
LC_MESSAGES="pl_PL.utf8"
LC_PAPER="pl_PL.utf8"
LC_NAME="pl_PL.utf8"
LC_ADDRESS="pl_PL.utf8"
LC_TELEPHONE="pl_PL.utf8"
LC_MEASUREMENT="pl_PL.utf8"
LC_IDENTIFICATION="pl_PL.utf8"
LC_ALL=

```

**Comment by raghur** [comment]
Thanks for the bug report. I've pushed an update to pypi that should fix this. Feel free to reopen if you run into trouble.

**Comment by snakefromhell** [comment]
Thanks for the update, it did the tricks. 

Now I get _UnicodeEncodeError_ in _blogger.blogger.ContentArgParser_

`easyblogger file post_title_number_only.markdown`

```
{u'aliases': [u'http://blog_url_.blogspot.com/2018/04/post_title_number_only.html'], u'title': u'post_title_number_only', u'draft': False, u'tags': [u'post_tag_number_only1', u'post_tag_number_only2', u'post_tag_number_only_etc']}
In processItem
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/blogger/main.py", line 274, in processItem
    fmt=args.format)
  File "/usr/local/lib/python2.7/dist-packages/blogger/blogger.py", line 239, in post
    markup = self._getMarkup(content, fmt, filters)
  File "/usr/local/lib/python2.7/dist-packages/blogger/blogger.py", line 197, in _getMarkup
    encodedBytes = bytes(raw).encode("utf8")
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 2: ordinal not in range(128)
Sat Apr 28 21:39:07 2018 <Greenlet at 0x7f61eb47f0f0: processItem(Namespace(blogid='_myblogid_', clientid=', <blogger.blogger.ContentArgParser object at 0x7f61)> failed with UnicodeEncodeError
```

**Comment by raghur** [comment]
Pushed another fix to pypi - upgrade package and try. 
Unicode on py27 is a pain... If you have the option try using py3.

**Comment by snakefromhell** [comment]
`Successfully installed EasyBlogger-2.1.1`

Same command same error but in diffrent lines. 
```
In processItem
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/blogger/main.py", line 274, in processItem
    fmt=args.format)
  File "/usr/local/lib/python2.7/dist-packages/blogger/blogger.py", line 240, in post
    markup = self._getMarkup(content, fmt, filters)
  File "/usr/local/lib/python2.7/dist-packages/blogger/blogger.py", line 199, in _getMarkup
    fp.write(encodedBytes)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 2: ordinal not in range(128)

```
Also 

**○ → which python**
`/usr/bin/python`
**○ → ls -al /usr/bin/python**
`lrwxrwxrwx 1 root root 9 mar 16  2015 /usr/bin/python -> python2.7`

Command-line completion on python reveal 

```
python                 python2-config         python3m
python2                python3                python-config
python2.7              python3.4              python_version_prompt
python2.7-config       python3.4m             
```
How I can set up a virtualenv for folder project witch py3 or py34 avoid broken apt-get. This question also reveals My programming experience.

**Comment by raghur** [comment]
> How I can set up a virtualenv for folder project witch py3 or py34 avoid broken apt-get. This question also reveals My programming experience.

You don't need a virtualenv... to run py3 version of easyblogger, just remove the python2 version with pip. Then do a `pip3 install easyblogger` which will install into your py3 site packages and then when you run easyblogger, py3 is used.

**Comment by raghur** [comment]
Can you put up the file you're using on pastebin or here?

**Comment by snakefromhell** [comment]
Shure, passwd is easyblogger at https://cryptobin.co/g4n504k8
Also it was generated by easyblogger command `easyblogger get -p "post_number" -d markdown --write-files` and what was modifed is removed unused tags like id = "" publishdate = "" etc. 

Should I do remove of easyblogger from python2 and install it as py34 now or wait to test an update?

**Comment by raghur** [comment]
pushed 2.1.2. please try.

BTW, you should have 'format = 'markdown'' in your file - otherwise it tries to use asciidoc. Also, the header format has to use the legacy (See README)
