### ISSUE TITLE
Request improvement

### ISSUE THREAD

**Issue by fpusersuggest** [raghur/easyblogger#175]
Hello,
you tool is super fantastic and perfect. But it lacks just one thing: upload images on blogspot.
I mean, I have an htmlpage I want upload on blogspot.. there is also a folder with images. It upload the html file but not the images that are linked in the html file.
Would be really nice that automatically it uploads the images.

**Comment by raghur** [comment]
Blogger uses Google album archives - 
https://support.google.com/blogger/answer/41641?hl=en

You could just create the archive manually and link to it from your post.

As such, given that there can be a wide variety of image links etc and I no longer use Blogger,  I have no plans to take this up. However, if you want to take a shot at a PR and need an overview of the source layout, I'll be happy to help.

**Comment by fpusersuggest** [comment]
The only one way I know to upload photos is from blogger interface. But I can upload only one photo at a time. Now I have this post with dozen of photos then it would be better an automatic way.
I'm not a developer but I want try to add some code to do the trick.

**Comment by raghur** [comment]
I see what you mean... I thought you could upload pics to google photos,
archive them and then move them to the blogger folder in archives...
apparently not.

But there's lots of ways to address this that doesn't involve more blogger
code

1. Use a different service - say flickr (I've done that on my blogger
blog). They support embedding pretty well.
2. Upload to Google photos, use shareable link and embed that - see
https://embedgooglephotos.com/#features (I haven't used this myself)

**Comment by fpusersuggest** [comment]
No. I'll try to upload the photos on google drive with api, set public permission and it should return me the url. Then I'll substitute the html img src tag with the url from google drive.
