### ISSUE TITLE
i can't post via command

### ISSUE THREAD

**Issue by googlebest** [raghur/easyblogger#2]
![image](https://cloud.githubusercontent.com/assets/11713740/23406990/419ab764-fdf4-11e6-8666-1b560e07cb77.png)

**Comment by raghur** [comment]
Hmm - What do you have in `~/.easyblogger`? Or can you try adding `--blogid <your blogid>` arg and trying?

**Comment by googlebest** [comment]
oh. i forgot blogid, thank you
