### ISSUE TITLE
 is there a possibility to set the date when inserting a new blog post?

### ISSUE THREAD

**Issue by schmonet** [raghur/easyblogger#34]
To my understanding currently date and time can only be received when querying already existing Blogposts. Because I'm typically agrigate new blog posts offline to be uploaded with easy Blogger later on, i would like to keep the original creation date of the post content and set it explezitely within the command line during the insertion Prozess at a later point of time with easyblogger. Do you think this is possible?

**Comment by schmonet** [comment]
Ok thanks prompt I will check that tomorrow.

⁣Gesendet mit BlueMail ​

**Comment by schmonet** [comment]
It seems to be possible to set a Publishdate when inserting a new Post with Blogger 3 API:
https://developers.google.com/blogger/docs/3.0/reference/posts/insert
postsInsertAction.setFields("author/displayName,content,published,title,url");
But i am not sure if this date could be set to the past rather than a future date. I could not test yet. 
But i know that with the Web UI of Blogger i can change the date manually to the past after having published a new post.
How can i specify in the commandline the date with easyblogger when i use "-R" ?
Thanks!

**Comment by raghur** [comment]
I've started a branch with support to modify post's publish date with an initial stab.

**Comment by schmonet** [comment]
Great, many thanks! That sounds promising.

⁣Gesendet mit BlueMail ​

**Comment by raghur** [comment]
Do you mind giving it a spin? Install directly from github branch - directions here  - https://stackoverflow.com/a/20101940/287085

Branch: publish-date

**Comment by schmonet** [comment]
I installed https://git-scm.com/download/win
Then executed in CMD.exe with Admin-privilages: pip install git+https://github.com/raghur/easyblogger.git@publish-date
All seems fine: 
Collecting git+https://github.com/raghur/easyblogger.git@publish-date
Successfully installed EasyBlogger-3.0.1 chardet-3.0.4 pyyaml-3.13

easyblogger --blogid "XXXXX" post -t "Test 1.1.2018" -l "Test" -c "This is a testblog from the 1.1.2018" --publish

...works as usual with setting the publish-date to the current date/time of executing this command (today is 18.07.2018).

without "--publish" i get a draft, which i can see on the Blogspot.com-Web UI.

I can manually change the Date of the above shown post in Blogspot.com-Web UI to 1.1.2018.

How am i supposed to tell easyblogger, to use 1.1.2018 as publishdate?

**Comment by raghur** [comment]
Use --date with either the post or the update commands

easyblogger post --help or easyblogger update --help should print out help.

Date format is ISO - so 2018-01-01T10:00:00

**Comment by raghur** [comment]
@schmonet  - did you get a chance to try with `--date`?

**Comment by schmonet** [comment]
Yes i did! (Sorry, allready sent a feedback, but the reply-mail didn't show up here.)
Yes it seems to work. Many thanks! When i set the --date with a timecode like 2018-01-01T10:00:00, this shows up in the Web UI of my (german) blogger account as 1.1.2018, 2 am"Pacific Daylight"  (-8hrs).

**Comment by raghur** [comment]
No problem - Thanks for trying it out. It's strange that it defaults to PDT (UTC would have made sense, but then). I'd try sending an iso8601 date with the timezone offset - see https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

I haven't tried it myself

**Comment by schmonet** [comment]
strange...offset seems to be 7hrs not 8hrs. When i set the cmd to:
--date 2018-06-11T23:00:00-07:00
i get 23:00:00 on the 11th of June, when i set
--date 2018-06-11T01:00:00-07:00
i get 01:00:00 on the 11th of June
...so for me "-07:00" seems to do the job.
