### ISSUE TITLE
Make it so that posting a file twice won't publish?

### ISSUE THREAD

**Issue by didibus** [raghur/easyblogger#4]
Hey,

Good work on easyblogger, I really like it. I've noticed if you publish a file that uses the comment, the first time, it adds a draft and adds the postId to the comment. Now if I change a few things, and publish a gain, even if I have published to false, the draft will be published, instead of just updating the draft.

I'm not sure if this is intentional or a bug, if the former, you think that could be changed?

**Comment by raghur** [comment]
pushed 1.2.5 to pypi - can you try now?

**Comment by didibus** [comment]
It works, thank you.
