### ISSUE TITLE
Look for blog Id in address bar?

### ISSUE THREAD

**Issue by hemanta212** [raghur/easyblogger#67]
The blog id of blog is available in the address bar after logging into the blogger.  Is there a reason you are suggesting to look into source in your Read me file?

**Comment by raghur** [comment]
Not really - anything is fine... I'm usually not logged in.

**Comment by hemanta212** [comment]
Is it possible to include a feature where the tool takes a blog name and searches for blogid itself. 
You know it would be a handy feature to have. May need  bs4 lib btw.

**Comment by raghur** [comment]
Honestly, I don't see that being very useful. finding the blog id is a one time action that's easily performed using a browser (and probably faster to do)... so I don't see the point of adding it to the tool.
