### ISSUE TITLE
published=true not working for 'file' command

### ISSUE THREAD

**Issue by ahmedmohiduet** [raghur/easyblogger#97]
I am running `easyblogger file myfile.md` with my markdown content:
```
<!--
{Labels: 'helloworld,python,blank', PostId: '', Title: Hello python,
  format: markdown, published: true}

-->

# This is my content
testing easyblogger

sdfkjsdfsdfsd
sagdfgdfg
```
Every time I am running my command, I am getting a draft post in my drafts but no published  post in my blog.

**Comment by raghur** [comment]
Legacy frontmatter format - use `Published: true`

**Comment by ahmedmohiduet** [comment]
Aah...Didn't know it was case sensitive! :smile:
